[fcgi]
threads=4 # The number of threads to spawn in FCGI mode

[userdb]
backend="sqlite" # The backend to use for the user db

[userdb.sqlite]
location="userdb.sqlite" # The file path where the sqlite database is stored

[cache]
enabled=false
type="local" # Cache either inside (F)CGI process or use remote cache
replacement="lru" # The replacement strategy of the cache
strategy="always" # When to cache (always|never)

# Size of <type> in bytes. <type> can be raster, points, lines, polygons, plots, provenance
[cache.raster]
size=262144
[cache.points]
size=262144
[cache.lines]
size=262144
[cache.polygons]
size=262144
[cache.plots]
size=262144
[cache.provenance]
size=262144

[global]
debug=true # Global debug flag e.g. used in services
[global.opencl]
preferredplatform="0" # The preferred platform for OpenCL
forcecpu=false # Force OpenCL to use the CPU instead of GPU

[rasterdb]
backend="local" # Remote specifies to use a tileserver to fetch raster tiles instead of loading them from disk (local|remote)

#[rasterdb.tileserver]
#port=0 # Specify the port for starting the tileserver.
#[rasterdb.remote]
#host="" # Specify the host of the tileserver to connect to.
#port=0 # Specify the port of the tileserver to connect to.
#[rasterdb.local]
#location="" # Specify the location for the local rasterdb to use for storing data.

#[featurecollectiondb]
#backend="postgres" # The backend for the featurecollectiondb
#[featurecollectiondb.postgres]
#location="postgresql://localhost/featurecollectiondb_test?user=user&password=pass&" # The SQL connection string e.g. user = 'user' host = 'localhost' password = 'pass' dbname = 'featurecollectiondb_test'. Note that the corresponding database needs to have the POSTGIS extension installed

[wms]
norasterforgiventimeexception=false # Configures the handling of NoRasterForGivenTimeException in WMS. If set to 0, a requested tile for a raster where there is no data for the given time results in a blank tile. If it is set to 1, the Exception is thrown.

#[gdalsource.datasets]
#path="" # The path to the JSON data set descriptions for the GDALSource

#[ogrsource.files]
#path="" # The path to the JSON data set descriptions for the OGRSource

[crsdirectory]
location="conf/crs.json" # The location of the file containing the definitions of the supported CRS

[operators.r]
location= "tcp:127.0.0.1:10200" # The connection string for the R-Operator to use when connecting to the rserver.

[uploader]
directory="uploader" # The name of the directory where the uploader stores the files

[log]
logtofile=false # If logs should be written to file instead of error stream
#logfilelocation="" # Location to store the logs
logfilelevel="DEBUG" # The maximum level to be logged to file
cgilogfilename="gci_logs.txt" # The name for CGI log file, that is shared between program instances.